[project]
name = "family-budget-reporting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.39.3",
    "pytest>=9.0.3",
    "python-dotenv>=1.2.2",
    "redmail>=0.6.0",
    "requests>=2.33.1",
]

[dependency-groups]
dev = [
    "anthropic>=0.88.0",
    "ipykernel>=7.2.0",
    "marimo>=0.22.0",
    "pandas>=3.0.2",
    "plotly>=6.6.0",
    "pyarrow>=23.0.1",
    "pydantic-ai-slim>=1.75.0",
    "pytest>=9.0.3",
    "python-lsp-server>=1.14.0",
]
