name: Monthly Budget Report (Docker)

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load secrets from Bitwarden
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
            a13c8960-b560-4de8-aa4e-b428012cbc82 > WALLET_API_TOKEN
            2b647326-c15c-4350-8f3b-b4290170ac6b > GMAIL_USERNAME
            d7a7df22-3379-497f-9240-b428012c8d86 > GMAIL_APP_PASSWORD

      - name: Build Docker image
        run: docker build -t budget-report .

      - name: Run Docker container
        run: |
          docker run --rm \
            -e WALLET_API_TOKEN=$WALLET_API_TOKEN \
            -e WALLET_BASE_URL=$WALLET_BASE_URL \
            -e GMAIL_USERNAME=$GMAIL_USERNAME \
            -e GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD \
            budget-report